### ISSUE TITLE
Packets dropped in v1.0, but correct in v0.1.2.

### ISSUE THREAD

**Issue by keck-in-space** [BallAerospace/python-ballcosmos#15]
Hello,

I have a script written that works fine with ballcosmos v0.1.2, but fails to collect all packets when using v1.0.0. I am running COSMOS v4.4.2

I have tried the script with ```os.environ["COSMOS_VERSION"] = "4"``` running ballcosmos v1.0.0, but it still fails in the same way.

What I am seeing is that after subscribing to a packet, the first few are dropped/missing with v1.0.0, but are always captured with v0.1.2.

```python
packet_queue = subscribe_packet_data([[PROJECT_NAME, DATA_PACKET_NAME]])
while True:
     # packets are missing here when using v1.0.0. They typically start a few behind the stream (4-6 packets are dropped)
    packet_data = (get_packet_data(packet_queue)[0]) 
```

**Comment by gerhardatball** [comment]
Hi @keck-in-space I just pushed an update the ballcosmos master branch to 1.1.0 and removed a lot of the changes I did for 1.0.0 if you can give it another try and see if you have the same problem. I was unable to reproduce the problem but we are going to keep ballcosmos for Cosmos v4 and will have a separate library for Cosmos v5.

**Comment by ryanatball** [comment]
Closing this due to lack of response.
