### ISSUE TITLE
Ready for COSMOS 5?

### ISSUE THREAD

**Issue by stanislaw** [BallAerospace/python-ballcosmos#20]
Before giving the latest master a try, I would like to know if the Python support is (almost?) ready for working with COSMOS 5.

We could reverse-engineer the Ruby scripting for COSMOS 5 and port it back to Python, but maybe this has already been done or being done by the COSMOS developers?

Any information on the status of COSMOS 5 support? Or any pointers on how we could give it a try and possibly send a PR if the migration is not too hard?..

Thank you.

**Comment by gerhardatball** [comment]
Still in progress but feel free to open bugs and pull requests: https://github.com/BallAerospace/python-cosmosc2
