### ISSUE TITLE
Queue invalidation occurring with subscription

### ISSUE THREAD

**Issue by keck-in-space** [BallAerospace/python-ballcosmos#22]
Hello,

I am using the ballcosmos library to subscribe to telemetry data. However, it looks like during times of high data rates, we see an error with the queue that we're using to receive data.

This is the error we see.

```
JsonDRb Error (-1): Packet data queue with id 1 not found
```

We have to resubscribe to get data again, which means we lose data during downlinks of large files.

Any ideas what we can do to fix this?

Thanks!

**Comment by ryanatball** [comment]
If queues overflow, they are deleted and that is the error you will receive.   

The solution is to make a larger queue when you subscribe.  The default is 1000 entries, but you can set it to whatever you need.  It will use RAM, so try to keep up servicing the queue.

https://cosmosc2.com/docs/v4/scripting#subscribe_packet_data
