### ISSUE TITLE
wait_check_expression no longer supports all ballcosmos functions

### ISSUE THREAD

**Issue by tfedak** [BallAerospace/python-ballcosmos#23]
In v1, wait_check_expression was in scripting.py and had a wildcard import on all ballcosmos functions, so it would evaluate any ballcosmos function you passed in. In v2, wait_check_expression is in api_shared.py which only has a handful of ballcosmos functions, so not all ballcosmos functions can be evaluated. Specifically, we ran into this using wait_check_expression on interface_state: "NameError: name ‘interface_state’ is not defined".

**Comment by ghost** [comment]
This is fixed in the 2.0.1 release today
