### ISSUE TITLE
"pip install" distribution is old version

### ISSUE THREAD

**Issue by nabelekt** [BallAerospace/python-ballcosmos#3]
I noticed that if I do a "pip install ballcosmos", I get ballcosmos-0.1.0, but the code is outdated. In the repo here, the print statements in script.py were removed when the last PR was merged (a6345454319d49ffb796a5ebd98baff09d6aa2f1). Those print statements still exist in the "pip install" distribution. How can we get that distribution updated?

Thanks.

**Comment by ryanatball** [comment]
Just uploaded 0.1.1 which includes this pull request.
