### ISSUE TITLE
Subscribe to commands

### ISSUE THREAD

**Issue by keck-in-space** [BallAerospace/python-ballcosmos#9]
Is there any way to subscribe to commands and receive them as they're sent? I know it is possible to subscribe the telemetry and receive a bytes object whenever telemetry is received. I'd like something like that, just for commands.

Thank you!

**Comment by ryanatball** [comment]
There is not an equivalent subscription API for commands in COSMOS 4.   You can connect a socket to the PREIDENTIFIED_ROUTER and get a TCP/IP stream of commands as they are sent, but we don't have any support code around doing that, like is provided with the subscribe_packet_data API.

In COSMOS 5 there is a new streaming API that you can receive either commands or telemetry with.
